/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { VNode } from "@stencil/core";
export { VNode } from "@stencil/core";
export namespace Components {
    interface MyComponent {
    }
    interface VirtualGrid {
        /**
          * @default 200
         */
        "itemMaxWidth": number;
        /**
          * @default []
         */
        "items": any[];
        "renderItem": (index: number) => VNode;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLVirtualGridElement extends Components.VirtualGrid, HTMLStencilElement {
    }
    var HTMLVirtualGridElement: {
        prototype: HTMLVirtualGridElement;
        new (): HTMLVirtualGridElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "virtual-grid": HTMLVirtualGridElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface VirtualGrid {
        /**
          * @default 200
         */
        "itemMaxWidth"?: number;
        /**
          * @default []
         */
        "items"?: any[];
        "renderItem"?: (index: number) => VNode;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "virtual-grid": VirtualGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "virtual-grid": LocalJSX.VirtualGrid & JSXBase.HTMLAttributes<HTMLVirtualGridElement>;
        }
    }
}
